/** STATE.AUTH */
const UPDATE_AUTH_VALID = 'UPDATE_AUTH_VALID'
const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
const UPDATE_AUTH       = 'UPDATE_AUTH'
const CLEAR_AUTH        = 'CLEAR_AUTH'

/** STATE.SAVINGS_GOAL_PAGE */
const UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM         = 'UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM'
const UPDATE_VIEW_SAVINGS_GOAL_PAGE              = 'SET_ADD_ERROR'
const UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM_PREVIEW = 'UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM_PREVIEW'

/** STATE.ADD_SAVINGS_GOAL_FORM */
const SHOW_ADD_SAVINGS_GOAL_FORM    = 'SHOW_ADD_SAVINGS_GOAL_FORM'
const HIDE_ADD_SAVINGS_GOAL_FORM    = 'HIDE_ADD_SAVINGS_GOAL_FORM'
const SET_ADD_SAVINGS_GOAL_ERROR    = 'SET_ADD_ERROR'
const SET_REMOVE_SAVINGS_GOAL_ERROR = 'SET_REMOVE_SAVINGS_GOAL_ERROR'

/** STATE.LOGIN_PAGE */
const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'

/** STATE.USER */
const UPDATE_USER = 'UPDATE_USER'
const CLEAR_USER  = 'CLEAR_USER'

 
const actions = {
    UPDATE_AUTH_VALID,
    UPDATE_AUTH_TOKEN,
    UPDATE_AUTH,
    CLEAR_AUTH,
    SHOW_ADD_SAVINGS_GOAL_FORM,
    HIDE_ADD_SAVINGS_GOAL_FORM,
    SET_REMOVE_SAVINGS_GOAL_ERROR,
    SET_ADD_SAVINGS_GOAL_ERROR,
    UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM_PREVIEW,
    UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM,
    UPDATE_VIEW_SAVINGS_GOAL_PAGE,
    SET_LOGIN_ERROR,
    UPDATE_USER,
    CLEAR_USER
}

export default actions