/** STATE.AUTH */
const UPDATE_AUTH_VALID = 'UPDATE_AUTH_VALID'
const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
const UPDATE_AUTH_ERROR = 'UPDATE_AUTH_ERROR'
const UPDATE_AUTH_USER  = 'UPDATE_AUTH_USER'
const UPDATE_AUTH       = 'UPDATE_AUTH'
const CLEAR_AUTH        = 'CLEAR_AUTH'

/** STATE.PAGE */
const UPDATE_PAGE_ITEM_PREVIEW = 'UPDATE_PAGE_ITEM_PREVIEW'
const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER'
const UPDATE_PAGE_ITEM   = 'UPDATE_PAGE_ITEM'
const UPDATE_PAGE        = 'SET_ADD_ERROR'

/** STATE.ITEM_FORM */
const SHOW_ITEM_FORM   = 'SHOW_ITEM_FORM'
const HIDE_ITEM_FORM   = 'HIDE_ITEM_FORM'
const SET_ADD_ERROR    = 'SET_ADD_ERROR'
const SET_REMOVE_ERROR = 'SET_REMOVE_ERROR'

const actions = {
    UPDATE_AUTH_VALID,
    UPDATE_AUTH_TOKEN,
    UPDATE_AUTH_ERROR,
    UPDATE_AUTH_USER,
    UPDATE_AUTH,
    CLEAR_AUTH,
    SHOW_ITEM_FORM,
    HIDE_ITEM_FORM,
    SET_REMOVE_ERROR,
    SET_ADD_ERROR,
    UPDATE_PAGE_ITEM_PREVIEW,
    UPDATE_PAGE_NUMBER,
    UPDATE_PAGE_ITEM,
    UPDATE_PAGE
}

export default actions