/** STATE.AUTH */
const UPDATE_AUTH_VALID = 'UPDATE_AUTH_VALID'
const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
const UPDATE_AUTH       = 'UPDATE_AUTH'
const CLEAR_AUTH        = 'CLEAR_AUTH'

/** STATE.SAVINGS_GOAL_PAGE */
const UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM         = 'UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM'
const UPDATE_VIEW_SAVINGS_GOAL_PAGE              = 'SET_ADD_ERROR'
const UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM_PREVIEW = 'UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM_PREVIEW'

/** STATE.ADD_SAVINGS_GOAL_FORM */
const SHOW_ADD_SAVINGS_GOAL_FORM    = 'SHOW_ADD_SAVINGS_GOAL_FORM'
const HIDE_ADD_SAVINGS_GOAL_FORM    = 'HIDE_ADD_SAVINGS_GOAL_FORM'
const SET_ADD_SAVINGS_GOAL_ERROR    = 'SET_ADD_ERROR'
const SET_REMOVE_SAVINGS_GOAL_ERROR = 'SET_REMOVE_SAVINGS_GOAL_ERROR'
const UPDATE_SAVINGS_GOAL_INPUTS = 'UPDATE_SAVINGS_GOAL_INPUTS'
const UPDATE_SAVINGS_GOAL_INPUT_ERRORS = 'UPDATE_SAVINGS_GOAL_INPUT_ERRORS'

/** STATE.LOGIN_PAGE */
const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
const RESET_LOGIN_PAGE = 'RESET_LOGIN_PAGE'
const UPDATE_LOGIN_INPUTS = 'UPDATE_LOGIN_INPUTS'
const UPDATE_SIGNUP_INPUTS = 'UPDATE_SIGNUP_INPUTS'
const UPDATE_LOGIN_INPUT_ERRORS = 'UPDATE_LOGIN_INPUT_ERRORS'
const UPDATE_SIGNUP_INPUT_ERRORS = 'UPDATE_SIGNUP_INPUT_ERRORS'
const LOGIN_PAGE_TOGGLE_IS_SAVING = 'LOGIN_PAGE_TOGGLE_IS_SAVING'
const LOGIN_PAGE_TOGGLE_IS_LOGIN_FORM = 'LOGIN_PAGE_TOGGLE_IS_LOGIN_FORM'
const LOGIN_PAGE_CLEAR_FORM = 'LOGIN_PAGE_CLEAR_FORM'
const LOGIN_PAGE_HANDLE_FORM_SWITCH_TO_SIGNUP = 'LOGIN_PAGE_HANDLE_FORM_SWITCH_TO_SIGNUP'
const LOGIN_PAGE_HANDLE_FORM_SWITCH_TO_LOGIN = 'LOGIN_PAGE_HANDLE_FORM_SWITCH_TO_LOGIN'

/** STATE.USER */
const UPDATE_USER = 'UPDATE_USER'
const CLEAR_USER  = 'CLEAR_USER'

 
const actions = {
    UPDATE_AUTH_VALID,
    UPDATE_AUTH_TOKEN,
    UPDATE_AUTH,
    CLEAR_AUTH,
    SHOW_ADD_SAVINGS_GOAL_FORM,
    HIDE_ADD_SAVINGS_GOAL_FORM,
    UPDATE_SAVINGS_GOAL_INPUTS,
    UPDATE_SAVINGS_GOAL_INPUT_ERRORS,
    SET_REMOVE_SAVINGS_GOAL_ERROR,
    SET_ADD_SAVINGS_GOAL_ERROR,
    UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM_PREVIEW,
    UPDATE_VIEW_SAVINGS_GOAL_PAGE_ITEM,
    UPDATE_VIEW_SAVINGS_GOAL_PAGE,
    SET_LOGIN_ERROR,
    RESET_LOGIN_PAGE,
    UPDATE_LOGIN_INPUTS,
    UPDATE_SIGNUP_INPUTS,
    UPDATE_LOGIN_INPUT_ERRORS,
    UPDATE_SIGNUP_INPUT_ERRORS,
    LOGIN_PAGE_TOGGLE_IS_SAVING,
    LOGIN_PAGE_TOGGLE_IS_LOGIN_FORM,
    LOGIN_PAGE_CLEAR_FORM,
    LOGIN_PAGE_HANDLE_FORM_SWITCH_TO_SIGNUP,
    LOGIN_PAGE_HANDLE_FORM_SWITCH_TO_LOGIN,
    UPDATE_USER,
    CLEAR_USER
}

export default actions
