const SAVINGS_GOALS_PAGE      = 0;
const VIEW_SAVINGS_ITEMS_PAGE = 1;
const BANK_ACCOUNTS_PAGE      = 2;
const PROFILE_PAGE            = 3;

export {
    SAVINGS_GOALS_PAGE,
    VIEW_SAVINGS_ITEMS_PAGE,
    BANK_ACCOUNTS_PAGE,
    PROFILE_PAGE
}